### ISSUE TITLE
Close on backdrop click

### ISSUE THREAD

**Issue by TheJaredWilcurt** [am283721/vue-my-photos#3]
Would be nice to have a boolean option to close the lightbox if the user clicks on the black backdrop.

**Comment by spanwair** [comment]
as a workaround you can make a layer over the lightbox when open and on click give
OPEN
```
showLightbox(imageName) {
      this.showBack = true;
      // @ts-ignore
      this.$refs.lightbox.show(imageName);
    },
```
CLOSE
```
hideLightbox() {
      this.showBack = false;
      // @ts-ignore
      this.$refs.lightbox.hide();
    },
```
DATA
 ```
data() {
    return {
      showBack: false,
    }
  },
```
HTML
`<div class="showBack" v-if="showBack" @click="hideLightbox()"></div>`
CSS
```
.showBack {
    position: fixed;
    width: calc(100% - 8rem);
    left: 4rem;
    top: 0;
    height: 100vh;
    z-index: 100000000000000;
  }
```

**Comment by florianmski** [comment]
I managed to do that in an easier way but probably a bit more nasty (not too familiar with web in general)

```js
mounted() {
    document.addEventListener('click', e => {
      if (e.target && e.target.className == 'lightbox-image') {
        this.hideLightbox()
      }
    });
  },
methods: {
    hideLightbox() {
      this.$refs.lightbox.hide();
    }
  }
```

This will close the lightbox anywhere you click except the previous / back arrows

**Comment by am283721** [comment]
This is long overdue for implementation. Let me see if I can get to it soon.

**Comment by am283721** [comment]
Better late than never?? This enhancement has been added in 1.1.0
